### ISSUE TITLE
Event Layer keeps loading forever after 500 error

### ISSUE THREAD

**Issue by Markionium** [dhis2/dhis2-gis#90] opened 2016-04-14 08:12 UTC
Not sure if this request makes sense... and is probably a server side bug :)

Reproduce: 
+ Open GIS (in dev https://play.dhis2.org/dev/dhis-web-mapping/#)
+ Edit Event Layer
+ On the Data tab select program `TB Program` and stage `test` then select all the available data items
+ For period select set `2010-04-14` to `2016-04-14`
+ For organisation unit select `User org unit`
+ Press update

![image](https://cloud.githubusercontent.com/assets/2134901/14521235/abb1fc34-0228-11e6-8f75-c48577efb4af.png)

**Comment by VladislavAlfredov** [comment] 2016-04-14 08:57
The following data item seems to be the cause of this: "testing data element".
I suspect that the data item has been added as a result of testing on the dev server.

**Comment by larshelge** [comment] 2016-04-14 13:58
Vlad - correct. After adding data elements one needs to re-run analytics before it can be used in analytics. This could be handled better but will require a completely new solution, out of scope for this release.

**Closed by larshelge** 2016-04-14 13:58 UTC
Labels: invalid

**Comment by Markionium** [comment] 2016-04-14 15:49
@larshelge @turban Agreed that it would be out of scope for this release, but i would say that displaying some sort of message to indicate that this "loading" is never going to end might be useful?
